spring:
  application:
    name: server-eureka
server:
  port: 1001 #启动端口

eureka:
  client:
      registerWithEureka: false  #false:不作为一个客户端注册到注册中心
      fetchRegistry: false
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false #false:不作为一个客户端注册到注册中心
#    fetch-registry: false
#  serviceUrl:
#      defaultZone: http://127.0.0.1:1001/eureka/