spring:
  application:
    name: server-eureka
server:
  port: 1001 #启动端口

#在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
eureka:
  client:
    register-with-eureka: false #false:不作为一个客户端注册到注册中心
    fetch-registry: false
  serviceUrl:
    defaultZone: http://127.0.0.1:1001/eureka/
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false #false:不作为一个客户端注册到注册中心
#    fetch-registry: false
#  serviceUrl:
#      defaultZone: http://127.0.0.1:1001/eureka/