spring:
  application:
    name: server-gateway

server:
  port: 1002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

gate:
  ignore:
    startWith: /auth/jwt

zuul:
  routes:
    api-a:
      path: /operation/**
      serviceId: operation-system
