spring:
  application:
    name: server-gateway

server:
  port: 1002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1001/eureka/

gate:
  ignore:
    startWith: /auth/jwt

zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
#    api-a:
#      path: /operation/**
#      serviceId: operation-system
#      strip-prefix: false
    operation:
      path: /operation/**
      url: http://localhost:8080/
      strip-prefix: false

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000