config-from: server-config-server-eureka-dev

server:
  port: 8761 #启动端口

#在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false #false:不作为一个客户端注册到注册中心
    fetch-registry: false
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    register-with-eureka: false #false:不作为一个客户端注册到注册中心
#    fetch-registry: false
#  serviceUrl:
#      defaultZone: http://127.0.0.1:1001/eureka/